### PR TITLE
This fix resolves an appeareance issue when spec is skipped. 

### PR DESCRIPTION
**Pull request by svett**
The skipped spec and the reason message should be in cyan color instead of red color.

### CODE REVIEW

**Comment by onsi** [comment]
Thanks for this. Super minor nit: could we make IsFailureState a method on SpecState instead of a package method?

**Comment by svett** [comment]
Good suggestion. Please check new commit that address this.

**Comment by onsi** [comment]
Thanks for braving the terribleness that is stenographer.go

**Comment by svett** [comment]
Many thanks!

**Pull request merged**
