### PR TITLE
Lack of test suites no longer breaks builds

### PR DESCRIPTION
**Pull request by andrehp**

### CODE REVIEW

**Comment by onsi** [comment]
Looks like the build broke:

/home/travis/gopath/src/github.com/onsi/ginkgo/integration/run_test.go:161

should be a quick fix if you have a moment to update the PR.  (sorry to be asking for such a basic PR -I'm away from my computer and making these changes on my iPad would be error-prone).

**Comment by benmoss** [comment]
you can just get rid of this assertion: https://github.com/onsi/ginkgo/blob/6adbc2648389a46e8ff0e96d07a07a9a9eb432de/integration/run_test.go#L157

**Comment by andrehp** [comment]
Yeah, sorry, I didn't notice there was a test as well. Fixed the PR

**Comment by charles-haynes** [comment]
How would you feel about putting this behavior under a command line option? I've lost a lot of time to this so I've already added it to a fork.

https://github.com/charles-haynes/ginkgo/commit/2202d205c5e87c307359c69b45105ed9e85cdc6a

**Comment by onsi** [comment]
sure. please shoot over a PR @charles-haynes  - the commit in your fork LGTM.

Can you also update the docs in the gh-pages branch to mention the flag?

**Comment by charles-haynes** [comment]
I've created a PR for the code, am doing the gh-pages now.

**Comment by benmoss** [comment]
Sorry about that @charles-haynes, I never envisioned this would cause so many problems :(

**Comment by charles-haynes** [comment]
no no @benmoss! Your work was super helpful. It was only when yet another new starter on our project had been bitten by it that I decided to go digging for a solution and what do you know - you had already done all the work. All I had to do was revive it and put it on a flag - voila! Thanks.

**Pull request merged**
