### PR TITLE
Adding Godep vendoring.

### PR DESCRIPTION
**Pull request by jayunit100**
Is this what we wanted for #240 @robdimsdale  @onsi  ?
Actually its my first time to play with the new `vendor/` stuff, seems to work ok for me so far.

### CODE REVIEW

**Comment by jayunit100** [comment]
(do not merge) This seems to for some reason not work for me - something about not liking the internal packages.

**Comment by jayunit100** [comment]
Ok, seems to be working now.

**Comment by onsi** [comment]
I'd really like to avoid using Godep please... I've commented on the other PR with a request to just manually vendor in the package.

**Comment by jayunit100** [comment]
Ok , This is just a PR to support the debate in the issue. I'll close and we can discuss in the issue

**Pull request closed without merging**
