### PR TITLE
Fix ginkgo import circle

### PR DESCRIPTION
**Pull request by BooleanCat**
The cycle is broken!

By using the latest gomega (with Go 1.18) and updating this go.mod to 1.18, we drop the transitive ginkgo dependencies.

### CODE REVIEW

**Comment by BooleanCat** [comment]
I've used an unreleased version of gomega at the moment, will update PR once gomega ships.

**Comment by onsi** [comment]
🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉

**Comment by onsi** [comment]
Just pushed out Gomega 1.19.0!

**Comment by BooleanCat** [comment]
Updated with v1.19.0. That go.sum diff is pretty satisfying 👌🏻

**Pull request merged**
