### PR TITLE
Add JustAfterEach

### PR DESCRIPTION
**Pull request by lwr20**
Fixes issue #483

### CODE REVIEW

**Comment by nodo** [comment]
Hey @lwr20 

Thanks for your PR and apologies for the late reply. It looks good to me and I am happy to merge it. Would you be able to resolve the conflict in the `.gitignore`?

Also, could you add a paragraph to the docs explaining `JustAfterEach`? You can follow the style of `JustBeforeEach` (see [here](http://onsi.github.io/ginkgo/#separating-creation-and-configuration-justbeforeeach)).

**Comment by lwr20** [comment]
That's great news, thanks!  I'll find some time to do those things next week.  

Dumb question time now - where would I find the docs to add that paragraph?

**Comment by williammartin** [comment]
@lwr20 @nodo Did we ever get docs for this? I'd like to merge.

**Comment by lwr20** [comment]
You haven't received docs for this yet and that's my fault.  I'll try to knock something up today.

**Comment by lwr20** [comment]
Docs update in #533

**Comment by williammartin** [comment]
I had a play around with this just now, the behaviour is intuitive if you know JustBeforeEach, but here's the sample I used anyway:
```
var _ = Describe("Testing Just After Eaches", func() {

	BeforeEach(func() {
		fmt.Println("BeforeEach")
	})

	JustBeforeEach(func() {
		fmt.Println("JustBeforeEach")
	})

	When("in a context", func() {

		BeforeEach(func() {
			fmt.Println("NestedBeforeEach")
		})

		JustBeforeEach(func() {
			fmt.Println("NestedJustBeforeEach")
		})

		It("does more stuff", func() {
			fmt.Println("It")
		})

		JustAfterEach(func() {
			fmt.Println("NestedJustAfterEach")
		})

		AfterEach(func() {
			fmt.Println("NestedAfterEach")
		})

	})

	JustAfterEach(func() {
		fmt.Println("JustAfterEach")
	})

	AfterEach(func() {
		fmt.Println("AfterEach")
	})
})
```

**Pull request merged**
