### PR TITLE
docs: added TOC for ver2

### PR DESCRIPTION
**Pull request by prashantgupta24**
Added a table of contents to the already awesome readme file

### CODE REVIEW

**Comment by prashantgupta24** [comment]
@onsi Do you think you can merge this in? It's really hard to go through the docs without a TOC

**Comment by onsi** [comment]
The new docs site will have a TOC on the sidebar.  Should make it easier to go through and won't need to be manually maintained separately...

**Comment by onsi** [comment]
It looks like this:

image

**Comment by prashantgupta24** [comment]
That's awesome! Will wait for that then.

**Pull request closed without merging**
