### PR TITLE
Add label to serial nodes

### LINKED ISSUE #1483: Add ability to filter for tested marked with "Serial"
Today, "Serial" is not a real label and thus it is impossible to filter by.
It would be great if we could grab serial tests by using this label instead of adding one of our own

### PR DESCRIPTION
**Pull request by akalenyu**
Adding a label in order to be able to filter tests decorated with `Serial`.

Fixes #1483

### CODE REVIEW

**Comment by akalenyu** [comment]
@onsi Are the failures caused by the PR?

**Comment by onsi** [comment]
yes - this line:

https://github.com/onsi/ginkgo/blob/master/integration/timeline_test.go#L141

needs to changed to `a full timeline [Serial]\n`

you should be able to `ginkgo -r -p` from the root directory and see it all go green.  Every now and then an integration spec will flake on a slow machine but they are generally pretty reliable so if you see a failure it’s _probably_ the new code.  In this case adding `Serial` as a label changed the output and we’ll need to update the test.

**Comment by akalenyu** [comment]
> yes - this line:
> 
> https://github.com/onsi/ginkgo/blob/master/integration/timeline_test.go#L141
> 
> needs to changed to `a full timeline [Serial]\n`
> 
> you should be able to `ginkgo -r -p` from the root directory and see it all go green. Every now and then an integration spec will flake on a slow machine but they are generally pretty reliable so if you see a failure it’s _probably_ the new code. In this case adding `Serial` as a label changed the output and we’ll need to update the test.

Added. I couldn't understand who sets the serial decorator on this timeline test though

**Comment by onsi** [comment]
yay! that worked.  will cut a release soon

**Comment by akalenyu** [comment]
> yay! that worked. will cut a release soon

hey, are you planning to cut a release?

**Comment by onsi** [comment]
done!

**Pull request merged**
