### PR TITLE
Handle -outputdir flag

### LINKED ISSUE #89: When running against multiple packages, `ginkgo --cover` should generate a composite coverfile and emit a single coverage percentage

### PR DESCRIPTION
**Pull request by AlexeySoshin**
Fixes #89

### CODE REVIEW

**Comment by onsi** [comment]
I think this looks good @AlexeySoshin - can you fix up the conflicts and I'll merge this today?

**Comment by onsi** [comment]
Also - do you mind submitting a PR to the gh-pages branch updating the documentation for the `-cover` related flags?  The right section is under "Running the race detector and code coverage tools:"

Thanks!

**Comment by onsi** [comment]
Great!  You up for a docs PR?

**Comment by AlexeySoshin** [comment]
@onsi Of course I am :)

**Comment by onsi** [comment]
Thanks!!

**Pull request merged**
