### PR TITLE
megalinter spell and cspell linting

### PR DESCRIPTION
**Pull request by dschveninger**
We are using ginkgo and while learning about the tool I have found the following spelling issues in the code base so I creating this PR to help out and thank you for a great tool.

### CODE REVIEW

**Comment by onsi** [comment]
hey thanks for this - I'll pull it in in a bit.  I'm in the middle of a big chunk of work and will need to rebase this onto my feature branch.

**Comment by onsi** [comment]
thanks for fixing that test failure!

**Comment by dschveninger** [comment]
You are welcome. Thank you for a great open source product.

**Comment by dschveninger** [comment]
Thanks

**Pull request merged**
